name: Publish

on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #     - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.8f1
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      - uses: webbertakken/unity-builder@v1.1
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Useful for debugging GitHub Action problems
      # - uses: actions/upload-artifact@v2
      #   with:
      #     if-no-files-found: error
      #     name: ${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
      #     path: build

      - name: Convert Unity target platform into itch.io channel
        run: |
          CHANNEL=${TARGET_PLATFORM/Standalone/}
          CHANNEL=${CHANNEL/64/}
          CHANNEL=${CHANNEL,,}
          echo "From target platform [${TARGET_PLATFORM}] to channel [${CHANNEL}]"
          echo "::set-env name=CHANNEL::$CHANNEL"
        env:
          TARGET_PLATFORM: ${{ matrix.targetPlatform }}

      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ env.CHANNEL }}
          ITCH_GAME: retro-brick-game
          ITCH_USER: beercan
          PACKAGE: build
