name: Publish

on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #     - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.12f1
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customImage: gableroux/unity3d:2019.4.12f1-update-2020-10-08

      - name: Convert Unity target platform into itch.io channel
        run: |
          CHANNEL=${TARGET_PLATFORM/Standalone/}
          CHANNEL=${CHANNEL/64/}
          CHANNEL=${CHANNEL,,}
          echo "From target platform [${TARGET_PLATFORM}] to channel [${CHANNEL}]"
          echo "::set-env name=CHANNEL::$CHANNEL"
        env:
          TARGET_PLATFORM: ${{ matrix.targetPlatform }}

      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ env.CHANNEL }}
          ITCH_GAME: retro-brick-game
          ITCH_USER: beercan
          PACKAGE: build
